### ISSUE TITLE
Copy-Calcy String contains Whitespaces

### ISSUE THREAD

**Issue by humpalum** [esauvisky/PGo-CalcaBotaBotaCalca#6]
When using "{calcy}" in as the rename string, the string contains some weird whitespaces, which causes, that the pkmn dont get renamed:
![image](https://user-images.githubusercontent.com/11175099/55947737-57663a80-5c4f-11e9-88df-296dc3182443.png)

Pasted into calcyIV:
![image](https://user-images.githubusercontent.com/11175099/55947841-8ed4e700-5c4f-11e9-91e8-2409d63513d5.png)

Pasting to a Pkmn:
![rname](https://user-images.githubusercontent.com/11175099/55948149-36eab000-5c50-11e9-9a51-587658ed99ef.gif)

**Comment by humpalum** [comment]
I was dumb and didnt post the calcIV string at the End but replaced the whole string

**Comment by esauvisky** [comment]
The non breaking spaces are precisely the workaround for the script to grab the data without them showing on the pokémon's name 😅
